language: objective-c
#xcode_project: JSONSchemaValidatorKit.xcodeproj # path to your xcodeproj folder
#xcode_scheme: JSONSchemaValidatorKit
osx_image: xcode7.3
#xcode_sdk: iphonesimulator9.3
script:
    - xcodebuild clean build -project JSONSchemaValidatorKit.xcodeproj -scheme JSONSchemaValidatorKit CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - xcodebuild clean test -project JSONSchemaValidatorKit.xcodeproj -scheme Unbox-iOS -destination "platform=iOS Simulator,name=iPhone 6" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
